Repository GarudaHacks/gh-6.0-site, pull requests merged in 2025-03, with the labels that each got.

#17 FAQ component created
  app/sections/FAQ.tsx
  package-lock.json
  package.json
Labels: Review effort 2/5

#19 Update Docker image
  .github/workflows/pr_agent.yml
Labels: Review effort 1/5

#18 Collapsible Tracks Component with Dynamic Expansion
  app/data/tracks.ts
  app/sections/Tracks.tsx
  package-lock.json
  package.json
Labels: Review effort 4/5
